update `shimpyo`.`question_table` set `question` = "오늘 하늘의 달 모양은?" where `dayofyear` = 64;
update `shimpyo`.`question_table` set `question` = "영원히 사라지지 않았으면 하는 장소가 있다면?" where `dayofyear` = 65;
update `shimpyo`.`question_table` set `question` = "오늘 기분을 의미할 수 있는 노래를 하나 꼽아본다면?" where `dayofyear` = 66;
update `shimpyo`.`question_table` set `question` = "나와 닮았다고 생각하는 동물 (성격도, 외모도 상관없어요)" where `dayofyear` = 67;
update `shimpyo`.`question_table` set `question` = "가장 좋아하는 음식은?" where `dayofyear` = 68;
update `shimpyo`.`question_table` set `question` = "요즘 가장 그리운 것은?" where `dayofyear` = 69;
update `shimpyo`.`question_table` set `question` = "오늘이 나의 마지막 날이라면 무엇을 하고 싶은가요?" where `dayofyear` = 70;
update `shimpyo`.`question_table` set `question` = "내 인생영화 Top3" where `dayofyear` = 71;
update `shimpyo`.`question_table` set `question` = "배우고 싶은 게 있다면?" where `dayofyear` = 72;
update `shimpyo`.`question_table` set `question` = "해보고 싶은 요리는?" where `dayofyear` = 73;
update `shimpyo`.`question_table` set `question` = "난 나에게 어떤 사람인가?" where `dayofyear` = 74;
update `shimpyo`.`question_table` set `question` = "난 타인에게 어떤 사람으로 비춰질까?" where `dayofyear` = 75;
update `shimpyo`.`question_table` set `question` = "내가 가장 나다워 지는 순간은?" where `dayofyear` = 76;
update `shimpyo`.`question_table` set `question` = "나의 버릇은?" where `dayofyear` = 77;
update `shimpyo`.`question_table` set `question` = "아무리 노력해도 고치기 어려운 단점은?" where `dayofyear` = 78;
update `shimpyo`.`question_table` set `question` = "나의 가장 큰 장점은?" where `dayofyear` = 79;
update `shimpyo`.`question_table` set `question` = "올해가 가기 전에 꼭 이루고 싶은 목표는?" where `dayofyear` = 80;
update `shimpyo`.`question_table` set `question` = "내가 생각하는 행복에 기준을 맞추려면 얼만큼의 돈이 필요한가?" where `dayofyear` = 81;
update `shimpyo`.`question_table` set `question` = "평생 이루고 싶은 목표가 있다면?" where `dayofyear` = 82;
update `shimpyo`.`question_table` set `question` = "가장 좋아하는 구절은?" where `dayofyear` = 83;
update `shimpyo`.`question_table` set `question` = "평생 남을 거 같은 기억은?" where `dayofyear` = 84;
update `shimpyo`.`question_table` set `question` = "평생 남을 거 같은 말 한마디" where `dayofyear` = 85;
update `shimpyo`.`question_table` set `question` = "" where `dayofyear` = 86;
update `shimpyo`.`question_table` set `question` = "나는 어떤 존재가 되고 싶은가?" where `dayofyear` = 87;
update `shimpyo`.`question_table` set `question` = "요즘 하고 있는 고민은?" where `dayofyear` = 88;
update `shimpyo`.`question_table` set `question` = "소비 패턴 중 가장 많은 비중을 차지하는 것은?" where `dayofyear` = 89;
update `shimpyo`.`question_table` set `question` = "나는 어떤 향기가 나는 사람인가?" where `dayofyear` = 90;
update `shimpyo`.`question_table` set `question` = "매일 __ 하고 싶어" where `dayofyear` = 91;
update `shimpyo`.`question_table` set `question` = "온전히 나를 위해 하는 행동이 있다면?" where `dayofyear` = 92;
update `shimpyo`.`question_table` set `question` = "나에게 해주고 싶은 말은?" where `dayofyear` = 93;
update `shimpyo`.`question_table` set `question` = "나는 주변 사람에게 어떤 사람으로 남고 싶은가" where `dayofyear` = 94;
update `shimpyo`.`question_table` set `question` = "내가 가장 바보 같았던 순간은? " where `dayofyear` = 95;
update `shimpyo`.`question_table` set `question` = "지금 당장 떠날 수 있다면 가고 싶은 곳은?" where `dayofyear` = 96;
update `shimpyo`.`question_table` set `question` = "당신만의 은밀한 취미는?" where `dayofyear` = 97;
update `shimpyo`.`question_table` set `question` = "오래오래 간직하고 싶은 기억은?" where `dayofyear` = 98;
update `shimpyo`.`question_table` set `question` = "나에게 가장 사주고 싶은 선물은?" where `dayofyear` = 99;
update `shimpyo`.`question_table` set `question` = "남들이 나에 대해 이것만은 몰랐으면 하는 것은?" where `dayofyear` = 100;
update `shimpyo`.`question_table` set `question` = "지금 당장 하고 싶은 것은?" where `dayofyear` = 101;
update `shimpyo`.`question_table` set `question` = "‘나’라는 사람에 대해서 남들이 갖는 편견은?" where `dayofyear` = 102;
update `shimpyo`.`question_table` set `question` = "‘나’라는 사람에 대해서 내가 갖는 편견은?" where `dayofyear` = 103;
update `shimpyo`.`question_table` set `question` = "나의 인생에 가장 큰 영향을 준 사람은?" where `dayofyear` = 104;
update `shimpyo`.`question_table` set `question` = "내 인생 맛집 Top3" where `dayofyear` = 105;
update `shimpyo`.`question_table` set `question` = "진심으로 미안했지만, 사과하지 못한 일이 있다면?" where `dayofyear` = 106;
update `shimpyo`.`question_table` set `question` = "요즘 나의 최대 관심사는?" where `dayofyear` = 107;
update `shimpyo`.`question_table` set `question` = "나만의 로망이 있다면?" where `dayofyear` = 108;
update `shimpyo`.`question_table` set `question` = "내가 살집을 짓는다면 어떤 집으로?" where `dayofyear` = 109;
update `shimpyo`.`question_table` set `question` = "나는 가족들에게 어떤 존재인가?" where `dayofyear` = 110;
update `shimpyo`.`question_table` set `question` = "나와 가장 잘 어울리는 과일은?" where `dayofyear` = 111;
update `shimpyo`.`question_table` set `question` = "만약 초능력을 갖게 된다면 어떤 초능력으로?" where `dayofyear` = 112;
update `shimpyo`.`question_table` set `question` = "사랑에 빠진 내 모습은?" where `dayofyear` = 113;
update `shimpyo`.`question_table` set `question` = "시작하고 싶은 취미활동은?" where `dayofyear` = 114;
update `shimpyo`.`question_table` set `question` = "나의 취미활동은?" where `dayofyear` = 115;
update `shimpyo`.`question_table` set `question` = "내가 세운 업적 중에 가장 뿌듯한 것은?" where `dayofyear` = 116;
update `shimpyo`.`question_table` set `question` = "나의 말버릇은?" where `dayofyear` = 117;
update `shimpyo`.`question_table` set `question` = "내가 요즘 가장 많이 하는 말은?" where `dayofyear` = 118;
update `shimpyo`.`question_table` set `question` = "나의 노래방 애창곡 Top3" where `dayofyear` = 119;
update `shimpyo`.`question_table` set `question` = "나에게 시간이 갈수록 소중해지는 것은?" where `dayofyear` = 120;